export const dynamic = "force-dynamic";

import type { Metadata } from "next";
import Link from "next/link";
import { TrendingUp, TrendingDown, Minus } from "lucide-react";
import { prisma } from "@/lib/db";
import { formatCurrency } from "@/lib/format";

export const metadata: Metadata = {
  title: "Daily Indian Market Summary — AI-generated end-of-day wrap",
  description:
    "AI-generated end-of-day Indian market summary: top gainers, losers, FII/DII flows, sentiment, and a 200-word narrative wrap. Updated daily after market close.",
  alternates: { canonical: "/daily-summary" },
};

interface Mover {
  name: string;
  slug: string;
  pct: number;
  close: number;
}

export default async function DailySummaryPage() {
  const latest = await prisma.marketSummary.findFirst({ orderBy: { date: "desc" } });
  const recent = await prisma.marketSummary.findMany({
    where: { date: { lt: latest?.date ?? new Date() } },
    orderBy: { date: "desc" },
    take: 7,
    select: { date: true, headline: true, sentiment: true },
  });

  if (!latest) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-10">
        <h1 className="text-2xl font-bold text-gray-900 mb-2">Daily Market Summary</h1>
        <div className="card text-center py-10 text-sm text-gray-500">
          No market summary yet. The first wrap publishes after the next 16:30 IST cron run.
        </div>
      </div>
    );
  }

  const sentimentIcon = latest.sentiment === "bullish" ? <TrendingUp className="w-4 h-4 text-green-600" /> : latest.sentiment === "bearish" ? <TrendingDown className="w-4 h-4 text-red-600" /> : <Minus className="w-4 h-4 text-gray-500" />;
  const sentimentColor = latest.sentiment === "bullish" ? "bg-green-50 text-green-700 border-green-200" : latest.sentiment === "bearish" ? "bg-red-50 text-red-700 border-red-200" : "bg-gray-50 text-gray-700 border-gray-200";
  const fiiNet = latest.fiiNet ? Number(latest.fiiNet) : null;
  const diiNet = latest.diiNet ? Number(latest.diiNet) : null;

  const topGainers = (latest.topGainers as Mover[] | null) ?? [];
  const topLosers = (latest.topLosers as Mover[] | null) ?? [];

  const dateLabel = new Intl.DateTimeFormat("en-IN", { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(latest.date);

  return (
    <div className="max-w-5xl mx-auto px-4 py-8 space-y-6">
      <div>
        <div className="flex items-center gap-2 mb-1">
          <h1 className="text-2xl md:text-3xl font-bold text-gray-900">Daily Market Summary</h1>
          {latest.sentiment ? (
            <span className={`px-2.5 py-1 rounded-lg border text-xs font-semibold inline-flex items-center gap-1 ${sentimentColor}`}>
              {sentimentIcon} {latest.sentiment}
            </span>
          ) : null}
        </div>
        <p className="text-sm text-gray-600">{dateLabel}</p>
      </div>

      {/* Headline + Body */}
      <div className="card">
        <h2 className="text-lg font-bold text-gray-900 mb-2">{latest.headline}</h2>
        <div className="text-sm text-gray-700 whitespace-pre-wrap leading-relaxed">{latest.body}</div>
        {latest.generatedBy ? (
          <p className="text-[11px] text-gray-400 mt-3">Generated by {latest.generatedBy}. Numbers are sourced from BSE EOD bhavcopy + NSE FII/DII reports — verify before acting.</p>
        ) : null}
      </div>

      {/* FII/DII */}
      <div className="grid grid-cols-2 gap-3">
        <div className="card">
          <div className="text-xs text-gray-500">FII net (Cr)</div>
          <div className={`text-2xl font-bold tabular-nums ${fiiNet == null ? "text-gray-500" : fiiNet >= 0 ? "text-green-600" : "text-red-600"}`}>
            {fiiNet == null ? "—" : `${fiiNet >= 0 ? "+" : ""}${formatCurrency(fiiNet * 10000000)}`}
          </div>
        </div>
        <div className="card">
          <div className="text-xs text-gray-500">DII net (Cr)</div>
          <div className={`text-2xl font-bold tabular-nums ${diiNet == null ? "text-gray-500" : diiNet >= 0 ? "text-green-600" : "text-red-600"}`}>
            {diiNet == null ? "—" : `${diiNet >= 0 ? "+" : ""}${formatCurrency(diiNet * 10000000)}`}
          </div>
        </div>
      </div>

      {/* Movers */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="card">
          <h3 className="text-sm font-semibold text-gray-900 mb-2 inline-flex items-center gap-1"><TrendingUp className="w-4 h-4 text-green-600" /> Top gainers</h3>
          <div className="divide-y divide-gray-100">
            {topGainers.map((m) => (
              <Link key={m.slug} href={`/ticker/${m.slug}`} className="flex items-center justify-between py-2 hover:bg-gray-50 -mx-2 px-2 rounded">
                <span className="text-sm text-gray-800">{m.name}</span>
                <div className="text-right">
                  <div className="text-sm font-semibold text-green-600 tabular-nums">+{m.pct.toFixed(2)}%</div>
                  <div className="text-[11px] text-gray-500 tabular-nums">₹{m.close.toFixed(2)}</div>
                </div>
              </Link>
            ))}
            {topGainers.length === 0 ? <div className="text-sm text-gray-500 py-4 text-center">No data</div> : null}
          </div>
        </div>
        <div className="card">
          <h3 className="text-sm font-semibold text-gray-900 mb-2 inline-flex items-center gap-1"><TrendingDown className="w-4 h-4 text-red-600" /> Top losers</h3>
          <div className="divide-y divide-gray-100">
            {topLosers.map((m) => (
              <Link key={m.slug} href={`/ticker/${m.slug}`} className="flex items-center justify-between py-2 hover:bg-gray-50 -mx-2 px-2 rounded">
                <span className="text-sm text-gray-800">{m.name}</span>
                <div className="text-right">
                  <div className="text-sm font-semibold text-red-600 tabular-nums">{m.pct.toFixed(2)}%</div>
                  <div className="text-[11px] text-gray-500 tabular-nums">₹{m.close.toFixed(2)}</div>
                </div>
              </Link>
            ))}
            {topLosers.length === 0 ? <div className="text-sm text-gray-500 py-4 text-center">No data</div> : null}
          </div>
        </div>
      </div>

      {/* Recent days */}
      {recent.length > 0 ? (
        <div>
          <h3 className="text-sm font-semibold text-gray-900 mb-2">Past wraps</h3>
          <div className="card divide-y divide-gray-100 p-0 overflow-hidden">
            {recent.map((r) => (
              <div key={r.date.toISOString()} className="flex items-center justify-between px-4 py-3">
                <div>
                  <div className="text-sm font-medium text-gray-900">{r.headline}</div>
                  <div className="text-xs text-gray-500 mt-0.5">{new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(r.date)}</div>
                </div>
                {r.sentiment ? <span className="text-[11px] text-gray-500 capitalize">{r.sentiment}</span> : null}
              </div>
            ))}
          </div>
        </div>
      ) : null}
    </div>
  );
}
